# Generated by Django 4.1 on 2022-09-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_sno_blogcomment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post',
            new_name='article',
        ),
    ]
