# Generated by Django 4.1 on 2022-09-03 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_rename_post_blogcomment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
